apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rex-bucket
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Retain
parameters:
  objectStoreName: rex-store
  objectStoreNamespace: rook-ceph
  region: us-east-1
