{
 "title": "K8S - Nodes",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server", "query": "kube_node_info" }
  ]
 },
 "panels": [
  { "title": "Node - $server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "server" },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests_cpu_cores{node=\"${server:raw}\"}) by(node) / on(node) (0.01 * kube_node_status_allocatable_cpu_cores)) * on(node) group_left(label_node_type) kube_node_labels \n",
     "legendFormat": "{{label_node_type}}"
    }
   ]
  },
  {
   "title": "CPU Seconds",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", instance=\"${server:raw}\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory Request",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\", instance=\"${server:raw}\"}) by (instance)",
     "legendFormat": " "
    }
   ]
  },
  { "title": "Node - $server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests_cpu_cores{node=\"${server:raw}\"}) by(node) / on(node) (0.01 * kube_node_status_allocatable_cpu_cores)) * on(node) group_left(label_node_type) kube_node_labels \n",
     "legendFormat": "{{label_node_type}}"
    }
   ]
  },
  {
   "title": "CPU Seconds",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", instance=\"${server:raw}\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory Request",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\", instance=\"${server:raw}\"}) by (instance)",
     "legendFormat": " "
    }
   ]
  },
  { "title": "Node - $server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests_cpu_cores{node=\"${server:raw}\"}) by(node) / on(node) (0.01 * kube_node_status_allocatable_cpu_cores)) * on(node) group_left(label_node_type) kube_node_labels \n",
     "legendFormat": "{{label_node_type}}"
    }
   ]
  },
  {
   "title": "CPU Seconds",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", instance=\"${server:raw}\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory Request",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\", instance=\"${server:raw}\"}) by (instance)",
     "legendFormat": " "
    }
   ]
  },
  { "title": "Node - $server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests_cpu_cores{node=\"${server:raw}\"}) by(node) / on(node) (0.01 * kube_node_status_allocatable_cpu_cores)) * on(node) group_left(label_node_type) kube_node_labels \n",
     "legendFormat": "{{label_node_type}}"
    }
   ]
  },
  {
   "title": "CPU Seconds",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", instance=\"${server:raw}\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory Request",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\", instance=\"${server:raw}\"}) by (instance)",
     "legendFormat": " "
    }
   ]
  },
  { "title": "Node - $server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests_cpu_cores{node=\"${server:raw}\"}) by(node) / on(node) (0.01 * kube_node_status_allocatable_cpu_cores)) * on(node) group_left(label_node_type) kube_node_labels \n",
     "legendFormat": "{{label_node_type}}"
    }
   ]
  },
  {
   "title": "CPU Seconds",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", instance=\"${server:raw}\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory Request",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\", instance=\"${server:raw}\"}) by (instance)",
     "legendFormat": " "
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU Usage per namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[5m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Node Requested CPI",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((sum(sum(kube_pod_container_resource_requests_cpu_cores) by(pod) * on(pod) group_left(node) kube_pod_info) by(node)) / on(node) (0.01 * kube_node_status_allocatable_cpu_cores)) * on(node) group_left(label_node_type) kube_node_labels ",
     "legendFormat": "{{label_node_type}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}